// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA75qO1N-QALWTZ-hdINlCJpr9hucdHx2w',
    appId: '1:269697796755:web:2bca0b82b64635dc219b66',
    messagingSenderId: '269697796755',
    projectId: 'fruits-ecommerce-c00fc',
    authDomain: 'fruits-ecommerce-c00fc.firebaseapp.com',
    storageBucket: 'fruits-ecommerce-c00fc.firebasestorage.app',
    measurementId: 'G-DEKRDV0JK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXZFzpAnQAOTIN47AWxG9EK825Gz4uqdE',
    appId: '1:269697796755:android:c63331fddf82244d219b66',
    messagingSenderId: '269697796755',
    projectId: 'fruits-ecommerce-c00fc',
    storageBucket: 'fruits-ecommerce-c00fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lJrzMnE-8STtym9oqNGvs4mgJ7rwGls',
    appId: '1:269697796755:ios:540603e43ac889de219b66',
    messagingSenderId: '269697796755',
    projectId: 'fruits-ecommerce-c00fc',
    storageBucket: 'fruits-ecommerce-c00fc.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lJrzMnE-8STtym9oqNGvs4mgJ7rwGls',
    appId: '1:269697796755:ios:540603e43ac889de219b66',
    messagingSenderId: '269697796755',
    projectId: 'fruits-ecommerce-c00fc',
    storageBucket: 'fruits-ecommerce-c00fc.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA75qO1N-QALWTZ-hdINlCJpr9hucdHx2w',
    appId: '1:269697796755:web:9551d807dbfb1f5d219b66',
    messagingSenderId: '269697796755',
    projectId: 'fruits-ecommerce-c00fc',
    authDomain: 'fruits-ecommerce-c00fc.firebaseapp.com',
    storageBucket: 'fruits-ecommerce-c00fc.firebasestorage.app',
    measurementId: 'G-EGQEBGRLFC',
  );
}
